language: python

# Cache the pip files
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.nvm
    - node_modules
    - wger/node_modules

# Use container infrastructure
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# Python versions to test
python:
  - "2.7"
  - "3.4"
  - "3.5"

# Manually define here the combinations environment variables to test
# https://github.com/travis-ci/travis-ci/issues/1519
env:
  - TEST_MOBILE=True  DB=postgresql TRAVIS_NODE_VERSION="4"
  - TEST_MOBILE=True  DB=sqlite     TRAVIS_NODE_VERSION="4"
  - TEST_MOBILE=False DB=postgresql TRAVIS_NODE_VERSION="4"
  - TEST_MOBILE=False DB=sqlite     TRAVIS_NODE_VERSION="4"
  

# Install the application
install:
  # Update nvm and set wanted Node version.
  # We update nvm using the script method instead of git, which is selected
  # automatically, as git won't work because the $HOME/.nvm is not a git
  # repository and the directory is not empty.
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | METHOD=script bash
  - . $HOME/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION

  # Install requirements
  - pip install -r requirements_devel.txt
  - npm install
  - if [[ "$DB" = "postgresql" ]]; then pip install psycopg2; fi

  # Setup application
  - if [[ "$DB" = "sqlite" ]]; then invoke create-settings; fi
  - if [[ "$DB" = "postgresql" ]]; then invoke create-settings --database-type postgresql; fi

# Create test databases
before_script:
  - npm install -g gulp-cli
  - if [[ "$DB" = "postgresq" ]]; then psql -c 'DROP DATABASE IF EXISTS test_wger;' -U postgres; fi
  - if [[ "$DB" = "postgresql" ]]; then psql -c 'CREATE DATABASE test_wger;' -U postgres; fi

# Do the tests
script:
  # Formatting
  - pep8 wger

  # Javascript linting
  - gulp lint 

  # Regular application
  - python manage.py makemigrations --merge
  - coverage run --source='.' ./manage.py test


  # Code coverage
  - coverage report

  #Integrate Travis with Slack
notifications:
  slack: 
  - secure: "uhgN2+9sBKc97lthBiy2bCjoys8geV8fgTR0lvTmMpTqx+5KTqTW884uUCGAB06C01d
  /9uvyXhlHkg2+2hKUEdpofp/auYL5HQjUHj1cDt5ZcSTJAId6uWun/99MVLUp+zUUyxieUcYydqost
  kJD3ctlkskg73xURTrF+F3BaTCaJgrChNCVgzcDxOnMg+MwM40xJbYKjTdQ0t7bWNS3s7AR3Kp7t+Q
  01IFuLtnaQoqHs11g9naXBTDnYvKKcGgybl9vlUyMq1b5JL8ysc6uxGNIGLgOkB1z/2JDhNpLwIp+0
  1ptC6WVFPmCGDx54duCRexRTQzmzrGMrr2+yBn4ierNX0OkFQ75/Nv/1b8GkEwLlbJlpIs8Jg6E/f2
  HXw+nPYZpGwnx7zaXLNqkIjYx0gx+II4JWN6ulSIkI+uQwSOq8tMoBuW8mC19l5X65D9FxC1MEBv3O
  NwSrRySQhnV7GLv/GEtO1B/FfTpm264soEc9hZlwnms4nxEKldGTiTDElebWQhcO8+Dk2y9oCAhObN
  UEird2CSNHZNhKmDhEepLMMb1S+Gu/58gkwNDWvHHAki63YTRq/t+semMIgqzlk9cHM4PmnL/jKYyr
  gI8T6fVsBsIXreFD3LXJo2CUN5mdRw8DbjVgRSSiR0pMrcz0xYNsNcQYLTejL0E+3scz7I="

  email:
    on_success: never
    on_failure: never

