# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-31 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20180114_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='choice',
            field=models.CharField(choices=[('pm', 'planned meal'), ('cm', 'consumed meal')], default='pm', max_length=2),
        ),
    ]
