# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-01 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_mealitem_choice'),
        ('nutrition', '0003_merge'),
    ]

    operations = [
    ]
