# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-01 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='choice',
            field=models.CharField(choices=[('planned meal', 'planned meal'), ('consumed meal', 'consumed meal')], default='planned meal', max_length=13),
        ),
    ]
