# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-31 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180114_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='select_plan',
            field=models.CharField(default=1, max_length=5, verbose_name='Selected your plan'),
        ),
    ]
