# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-31 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180114_1734'),
        ('manager', '0008_auto_20180124_1624'),
    ]

    operations = [
    ]
