# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-02 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_merge'),
        ('manager', '0011_auto_20180201_1108'),
    ]

    operations = [
    ]
