# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-05 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_plan',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='select_plan',
        ),
    ]
