# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-05 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20180205_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_plan',
            field=models.BooleanField(default=False, verbose_name='Schedule a plan'),
        ),
    ]
