# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-05 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_remove_schedule_select_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='select_plan',
            field=models.CharField(default='1', max_length=5, verbose_name='Select your plan'),
        ),
    ]
